Update deploy_dev.yml

diff --git a/.github/workflows/deploy_dev.yml b/.github/workflows/deploy_dev.yml
--- a/.github/workflows/deploy_dev.yml
+++ b/.github/workflows/deploy_dev.yml
@@ -32,6 +32,7 @@ jobs:
         envs: FIREBASE_ADMIN_SDK,SECRETS_GMAP,SECRETS_FIREBASE,FRONTEND_ENV,SECRET_DATABASE_ENV, GCLOUD_CONSOLE_SA, SECRET_STRIPE
         script: |
           set -x  # Enable debug mode
+          set -e  # Exit on error
           
           echo "Starting deployment process..."
           
@@ -44,6 +45,8 @@ jobs:
           echo "Removed existing s_locator directory."
           
           # Clone the repository and update submodules
+          git config --global user.email "ci@example.com"
+          git config --global user.name "Github actions"
           git clone --recursive https://github.com/abdullahalhoothy/s_locator.git &&
           cd s_locator &&
           git submodule update --remote --recursive --merge &&
