Update deploy_prd.yml

diff --git a/.github/workflows/deploy_prd.yml b/.github/workflows/deploy_prd.yml
--- a/.github/workflows/deploy_prd.yml
+++ b/.github/workflows/deploy_prd.yml
@@ -24,16 +24,23 @@ jobs:
         FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
         SECRET_DATABASE_ENV: ${{ secrets.SECRET_DATABASE_ENV }}
         GCLOUD_CONSOLE_SA: ${{ secrets.GCLOUD_CONSOLE_SA }}
+        SECRET_STRIPE: ${{ secrets.SECRET_STRIPE }}
       with:
         host: ${{ secrets.VPS_HOST }}
         username: ${{ secrets.VPS_USERNAME }}
         key: ${{ secrets.VPS_SSH_KEY }}
-        envs: FIREBASE_ADMIN_SDK,SECRETS_GMAP,SECRETS_FIREBASE,FRONTEND_ENV,SECRET_DATABASE_ENV, GCLOUD_CONSOLE_SA
+        envs: FIREBASE_ADMIN_SDK,SECRETS_GMAP,SECRETS_FIREBASE,FRONTEND_ENV,SECRET_DATABASE_ENV, GCLOUD_CONSOLE_SA, SECRET_STRIPE
         script: |
           set -x  # Enable debug mode
+          set -e  # Exit on error
           
           echo "Starting deployment process..."
-          
+
+          cd ..
+          cd ..
+          cd ..
+          cd ..
+          cd ..
           if [ -d "s_locator" ]; then
             cd s_locator
             docker compose down
@@ -49,7 +56,7 @@ jobs:
           git config --global user.name "Github actions"
           git clone --recursive https://github.com/abdullahalhoothy/s_locator.git &&
           cd s_locator &&
-          git submodule update --remote --recursive --merge &&
+          git submodule update --remote --recursive &&
           git submodule foreach 'git checkout main && git pull origin main'
           echo "Repository cloned and submodules updated."
           
@@ -65,6 +72,8 @@ jobs:
           echo '${{ secrets.GCLOUD_CONSOLE_SA }}' > my_middle_API/secrets/weighty-gasket-437422-h6-a9caa84da98d.json
           echo '${{ secrets.SECRET_DATABASE_ENV }}' > storage/secrets/secrets_database.env
           echo '${{ secrets.FRONTEND_ENV }}' > FrontEnd/.env
+          echo '${{ secrets.GCLOUD_CONSOLE_SA }}' > my_middle_API/secrets/weighty-gasket-437422-h6-a9caa84da98d.json
+          echo '${{ secrets.SECRET_STRIPE }}' > my_middle_API/secrets/secret_stripe.json
           echo "Secret files created."
           
           # Replace values in files
